"""Generate the full ablation matrix from one template pair.

Takes a validated base/HLA config pair and emits one config per ablation arm,
each differing from base in EXACTLY the mechanism under test (single-factor
design). All arms share run-name conventions, save dirs and init paths, so
runs can be launched in a loop and plotted together.

Arms (single mechanism ON, everything else at base values):
  phase        : phase_mult only
  gates        : laplace_alpha only (K/V multiplicative gating)
  salience     : salience_alpha only
  distance     : distance_laplace_alpha only
  forget       : forget_alpha only (FoX-style cumulative gate = external
                 baseline mechanism reproduced inside the sterile harness)
Combined arms:
  full         : the HLA template as-is (all its mechanisms)
  full+temp    : full + learnable_layer_temp
  full+headphase : full + per_head_phase (+ layer_dependent_phase if ldg)

Usage:
  python scripts/make_ablation_configs.py \
      --base configs/200m_base_v2_s42.json --hla configs/200m_hla_v2_s42.json \
      --outdir configs/ablations_200m --seeds 42 43 44

Every emitted pair passes validate_configs.py by construction (only allowed
keys differ). Emits a MANIFEST.json with the full matrix for bookkeeping.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import sys

ZERO_KEYS = {
    "phase_mult": 0.0,
    "laplace_alpha": 0.0,
    "distance_laplace_alpha": 0.0,
    "salience_alpha": 0.0,
    "forget_alpha": 0.0,
}


def load(p: str) -> dict:
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def save(p: str, cfg: dict) -> None:
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")


def make_arm(base: dict, hla: dict, arm: str, seed: int, outdir: str) -> tuple[str, dict]:
    """Build one ablation config: base skeleton + selected HLA knobs."""
    cfg = copy.deepcopy(base)
    m = cfg["model"]
    hm = hla["model"]

    # start from all mechanisms OFF (base values)
    for k, v in ZERO_KEYS.items():
        m[k] = v
    # make sure structural flags exist so params match across all arms
    for k in ("use_laplace", "use_distance_laplace", "use_salience_bias", "use_forget_gate"):
        m[k] = True

    if arm == "base":
        pass
    elif arm == "phase":
        m["phase_mult"] = hm["phase_mult"]
    elif arm == "gates":
        m["laplace_alpha"] = hm.get("laplace_alpha", 1.0)
    elif arm == "salience":
        m["salience_alpha"] = hm.get("salience_alpha", 1.0)
        m["salience_range"] = hm.get("salience_range", m.get("salience_range", 2.0))
        m["salience_clip"] = hm.get("salience_clip", m.get("salience_clip", 3.0))
    elif arm == "distance":
        m["distance_laplace_alpha"] = hm.get("distance_laplace_alpha", 0.5)
    elif arm == "forget":
        m["use_forget_gate"] = True
        m["forget_alpha"] = 1.0
    elif arm == "full":
        for k in ZERO_KEYS:
            if k in hm:
                m[k] = hm[k]
    elif arm == "full_temp":
        for k in ZERO_KEYS:
            if k in hm:
                m[k] = hm[k]
        m["layer_dependent_gate"] = True
        m["learnable_layer_temp"] = True
    elif arm == "full_headphase":
        for k in ZERO_KEYS:
            if k in hm:
                m[k] = hm[k]
        m["per_head_phase"] = True
        if m.get("layer_dependent_gate", False):
            m["layer_dependent_phase"] = True
    else:
        raise ValueError(f"unknown arm: {arm}")

    cfg["seed"] = seed
    name = f"abl_{arm}_s{seed}"
    cfg["run_name"] = name
    cfg["save_dir"] = f"/kaggle/working/runs/{name}"
    cfg["init_ckpt"] = f"/kaggle/working/inits/init_abl_s{seed}.pt"  # SHARED init per seed!
    cfg["variant"] = f"ablation_{arm}"
    cfg["model"]["baseline_type"] = f"ablation_{arm}"
    cfg["_doc"] = (
        f"Single-factor ablation arm '{arm}', seed {seed}. All arms of one seed "
        f"share the same sterile init checkpoint; each arm differs from 'base' "
        f"arm only in its mechanism alphas. Generated by make_ablation_configs.py."
    )
    return name, cfg


ARMS = ["base", "phase", "gates", "salience", "distance", "forget",
        "full", "full_temp", "full_headphase"]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--hla", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--seeds", type=int, nargs="+", default=[42])
    ap.add_argument("--arms", nargs="+", default=ARMS, choices=ARMS)
    args = ap.parse_args()

    base, hla = load(args.base), load(args.hla)
    manifest = {"template_base": args.base, "template_hla": args.hla,
                "seeds": args.seeds, "arms": args.arms, "configs": []}

    for seed in args.seeds:
        for arm in args.arms:
            name, cfg = make_arm(base, hla, arm, seed, args.outdir)
            path = os.path.join(args.outdir, f"{name}.json")
            save(path, cfg)
            manifest["configs"].append(path)
            print(f"  wrote {path}")

    save(os.path.join(args.outdir, "MANIFEST.json"), manifest)
    n = len(args.seeds) * len(args.arms)
    print(f"\n{n} configs written to {args.outdir}")
    print("Launch order suggestion: for each seed -> make_init once (shared), "
          "then all arms; paired across arms by construction.")


if __name__ == "__main__":
    main()
